lib: [
  "_build/install/default/lib/c-formatter/META"
  "_build/install/default/lib/c-formatter/c_formatter.a"
  "_build/install/default/lib/c-formatter/c_formatter.cma"
  "_build/install/default/lib/c-formatter/c_formatter.cmi"
  "_build/install/default/lib/c-formatter/c_formatter.cmt"
  "_build/install/default/lib/c-formatter/c_formatter.cmx"
  "_build/install/default/lib/c-formatter/c_formatter.cmxa"
  "_build/install/default/lib/c-formatter/c_formatter.ml"
  "_build/install/default/lib/c-formatter/c_formatter__Config.cmi"
  "_build/install/default/lib/c-formatter/c_formatter__Config.cmt"
  "_build/install/default/lib/c-formatter/c_formatter__Config.cmx"
  "_build/install/default/lib/c-formatter/c_formatter__Formatter.cmi"
  "_build/install/default/lib/c-formatter/c_formatter__Formatter.cmt"
  "_build/install/default/lib/c-formatter/c_formatter__Formatter.cmx"
  "_build/install/default/lib/c-formatter/c_formatter__Lexer.cmi"
  "_build/install/default/lib/c-formatter/c_formatter__Lexer.cmt"
  "_build/install/default/lib/c-formatter/c_formatter__Lexer.cmx"
  "_build/install/default/lib/c-formatter/config.ml"
  "_build/install/default/lib/c-formatter/dune-package"
  "_build/install/default/lib/c-formatter/formatter.ml"
  "_build/install/default/lib/c-formatter/lexer.ml"
]
libexec: [
  "_build/install/default/lib/c-formatter/c_formatter.cmxs"
]
bin: [
  "_build/install/default/bin/c-formatter"
]
doc: [
  "_build/install/default/doc/c-formatter/README.md"
]
